controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_base_controller:
      type: diff_drive_controller/DiffDriveController
      left_wheel_names: ["left_wheel_joint"]
      right_wheel_names: ["right_wheel_joint"]
      wheel_separation: 0.30
      wheel_radius: 0.10
      use_stamped_vel: false
      publish_rate: 50.0
      cmd_vel_timeout: 0.5
      enable_odom_tf: true
      base_frame_id: "base_link"
      odom_frame_id: "odom"
      linear:
        x:
          has_velocity_limits: true
          max_velocity: 0.5
          has_acceleration_limits: true
          max_acceleration: 1.0
      angular:
        z:
          has_velocity_limits: true
          max_velocity: 1.0
          has_acceleration_limits: true
          max_acceleration: 2.0